Menus.UI/Models/ErrorViewModel.cs
namespace Menus.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Menus.UI/Models/VMMenus.cs
namespace Menus.UI.Models
{
	public class VMMenus
	{
		public int id_menu { get; set; }
		public string menu_titulo { get; set; }
	}
}

Menus.UI/Controllers/EventosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Menus.UI.Controllers
{
    public class EventosController : Controller
    {
        // GET: EventosController
        public ActionResult Index()
        {
            return View();
        }

  
    }
}

Menus.UI/Controllers/HomeController.cs
using Menus.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Menus.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Menus.UI/Controllers/MenuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Menus.UI.Controllers
{
    public class MenuController : Controller
    {
        // GET: MenuController
        public ActionResult Index()
        {
            return View();
        }

  
    }
}

Menus.UI/Views/Eventos/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <script src='~/fullcalendar/dist/index.global.js'></script>
    <script>

        document.addEventListener('DOMContentLoaded', function() {
          var calendarEl = document.getElementById('calendar');

          var calendar = new FullCalendar.Calendar(calendarEl, {
            headerToolbar: {
              left: 'prev,next today',
              center: 'title',
              right: 'dayGridMonth,timeGridWeek,timeGridDay,listMonth'
            },
            initialDate: '2023-03-16',
            navLinks: true, // can click day/week names to navigate views
            businessHours: true, // display business hours
            editable: true,
            selectable: true,
            events: [
              {
                title: 'Business Lunch',
                start: '2023-01-03T13:00:00',
                constraint: 'businessHours'
              },
              {
                title: 'Meeting',
                start: '2023-01-13T11:00:00',
                constraint: 'availableForMeeting', // defined below
                color: '#257e4a'
              },
              {
                title: 'Conference',
                start: '2023-01-18',
                end: '2023-01-20'
              },
              {
                title: 'Party',
                start: '2023-01-29T20:00:00'
              },

              // areas where "Meeting" must be dropped
              {
                groupId: 'availableForMeeting',
                start: '2023-01-11T10:00:00',
                end: '2023-01-11T16:00:00',
                display: 'background'
              },
              {
                groupId: 'availableForMeeting',
                start: '2023-01-13T10:00:00',
                end: '2023-01-13T16:00:00',
                display: 'background'
              },

              // red areas where no events can be dropped
              {
                start: '2023-01-24',
                end: '2023-01-28',
                overlap: false,
                display: 'background',
                color: '#ff9f89'
              },
              {
                start: '2023-01-06',
                end: '2023-01-08',
                overlap: false,
                display: 'background',
                color: '#ff9f89'
              }
            ]
          });

          calendar.render();
        });

    </script>
    <style>

        body {
            margin: 40px 10px;
            padding: 0;
            font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
            font-size: 14px;
        }

        #calendar {
            max-width: 1100px;
            margin: 0 auto;
        }

    </style>
</head>
<body>

    <div id='calendar'></div>

</body>
</html>

Menus.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>CALENDARIO UDLA-GYM</p>
</div>

Menus.UI/Views/Menu/Index.cshtml
@{
	ViewData["Title"] = "Menus";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card card-info">
	<div class="card-header">
		<h3 class="text-center">CREAR HORARIO</h3>
	</div>
	<div class="card-body">
		<div class="row">
			<div class="col">
				<input type="hidden" id="id_menu" value="" />
				<label>Coach:</label>
				<input type="text" class="form-control" placeholder="Coach" id="menu_coach" name="menu_coach">
			</div>
			<div class="col">
				<label>Alumno:</label>
				<input type="text" class="form-control" placeholder="Alumno" id="menu_alumno" name="menu_alumno">
			</div>
		</div>
		<br />
		<div class="row">
			<div class="col">
				<label>Ejercicio:</label>
				<input type="text" class="form-control" placeholder="Ejercicio" id="menu_ejer" name="menu_ejer">
			</div>
		</div>
		<br />
		<div class="row">
			<div class="col-6">
				<label>Fecha:</label>
				<input type="datetime-local" class="form-control" id="menu_fecha" name="menu_fecha">
			</div>
		</div>
		<br />
		<div class="row">
			<div class="col-md-6">
				<button id="btnsave" class="btn btn-success btn-sm">Guardar</button>
				<button id="btnAddnew" class="btn btn-primary btn-sm">Limpiar Datos</button>
			</div>
		</div>
		<br />
		<table id="tblmenu" class="table table-striped table-bordered" style="width: 100%">
			<thead>
				<tr>
					<th class="d-none">id_menu</th>
					<th>Coach</th>
					<th>Alumno</th>
					<th>Ejercicio</th>
					<th>Fecha</th>
				</tr>
			</thead>
			<tbody></tbody>
		</table>
	</div>
</div>
@section Scripts {
	<script src="~/js/Menu/Menu.js"></script>
}

Menus.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Menus.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Menus.UI.styles.css" asp-append-version="true" />
    <link href="~/DataTables/datatables.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UDLA GYM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="Index">Recordatorio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Index">Calendario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Menus.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="DataTables/datatables.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>  
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>